/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.collegeit.screen;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Katia Moreno * Student Number: 2015255
 * 
 */
public class ScreenMain extends javax.swing.JFrame {

    /**
     * Creates new form ScreenMain
     */
    public ScreenMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        lblUser = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MenAdm = new javax.swing.JMenu();
        MenAdmUse = new javax.swing.JMenuItem();
        MenAdmCou = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menStudentProfile = new javax.swing.JMenuItem();
        MenCou = new javax.swing.JMenu();
        menCourse = new javax.swing.JMenuItem();
        MenHel = new javax.swing.JMenu();
        MenHelAbo = new javax.swing.JMenuItem();
        MenOpt = new javax.swing.JMenu();
        MenOptExi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IT College - Main System ");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setPreferredSize(new java.awt.Dimension(680, 480));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblUser.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUser.setText("User");

        lblDate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDate.setText("Date");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/collegeit/icons/logo1.jpg"))); // NOI18N

        jLabel3.setText("Date");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Dashboard ");

        lblUserName.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblUserName.setText("User Name");

        MenAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/collegeit/icons/adm.png"))); // NOI18N
        MenAdm.setText("Administrator");
        MenAdm.setEnabled(false);

        MenAdmUse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        MenAdmUse.setText("User");
        MenAdmUse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAdmUseActionPerformed(evt);
            }
        });
        MenAdm.add(MenAdmUse);

        MenAdmCou.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        MenAdmCou.setText("Course");
        MenAdmCou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAdmCouActionPerformed(evt);
            }
        });
        MenAdm.add(MenAdmCou);

        Menu.add(MenAdm);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/collegeit/icons/if_Student-3_379413.png"))); // NOI18N
        jMenu1.setText("Student");

        menStudentProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menStudentProfile.setText("Profile");
        menStudentProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menStudentProfileActionPerformed(evt);
            }
        });
        jMenu1.add(menStudentProfile);

        Menu.add(jMenu1);

        MenCou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/collegeit/icons/college.icon.png"))); // NOI18N
        MenCou.setText("Course");

        menCourse.setText("Course");
        menCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCourseActionPerformed(evt);
            }
        });
        MenCou.add(menCourse);

        Menu.add(MenCou);

        MenHel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/collegeit/icons/information...png"))); // NOI18N
        MenHel.setText("Help");

        MenHelAbo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        MenHelAbo.setText("about");
        MenHelAbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenHelAboActionPerformed(evt);
            }
        });
        MenHel.add(MenHelAbo);

        Menu.add(MenHel);

        MenOpt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/collegeit/icons/exit...png"))); // NOI18N
        MenOpt.setText("Option");

        MenOptExi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenOptExi.setText("Exit");
        MenOptExi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenOptExiActionPerformed(evt);
            }
        });
        MenOpt.add(MenOptExi);

        Menu.add(MenOpt);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDate)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lblUser))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUserName)
                        .addGap(59, 59, 59))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(752, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(lblUserName)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(999, 631));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // the next line will show the current date when the system starts
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblDate.setText(formatador.format(data));
       
    }//GEN-LAST:event_formWindowActivated

    private void MenOptExiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenOptExiActionPerformed
        // Displays dialog box to exit the system
         int ex = JOptionPane.showConfirmDialog(null, "Are you sure, you want to turn off system?", "confirmation", JOptionPane.YES_NO_OPTION);
         if(ex == JOptionPane.YES_OPTION){
             System.exit(0);
         }
    }//GEN-LAST:event_MenOptExiActionPerformed

    private void MenHelAboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenHelAboActionPerformed
        // Call Display About
        ScreenAbout about =new ScreenAbout();
        about.setVisible(true);
        desktop.add(about);
    }//GEN-LAST:event_MenHelAboActionPerformed

    private void MenAdmUseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAdmUseActionPerformed
        // in the line below will open the user form in the desktop pane
        AdminDashboard user = new AdminDashboard();
        user.setVisible(true);
        desktop.add(user);
    }//GEN-LAST:event_MenAdmUseActionPerformed

    private void MenAdmCouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAdmCouActionPerformed
        // call the course Screen in Administrator screen
       AdminDashboardCourse course = new AdminDashboardCourse();
        course.setVisible(true);
        desktop.add(course);
    }//GEN-LAST:event_MenAdmCouActionPerformed

    private void menStudentProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menStudentProfileActionPerformed
        // call the Student Screen 
       StudentDashboard student = new StudentDashboard();
        student.setVisible(true);
        desktop.add(student);
    }//GEN-LAST:event_menStudentProfileActionPerformed

    private void menCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCourseActionPerformed
        // call the course Screen where the student can see the course
        ScreenCourse courses = new ScreenCourse();
        courses.setVisible(true);
        desktop.add(courses);
    }//GEN-LAST:event_menCourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu MenAdm;
    private javax.swing.JMenuItem MenAdmCou;
    private javax.swing.JMenuItem MenAdmUse;
    private javax.swing.JMenu MenCou;
    private javax.swing.JMenu MenHel;
    private javax.swing.JMenuItem MenHelAbo;
    private javax.swing.JMenu MenOpt;
    private javax.swing.JMenuItem MenOptExi;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel lblDate;
    public static javax.swing.JLabel lblUser;
    public static javax.swing.JLabel lblUserName;
    private javax.swing.JMenuItem menCourse;
    private javax.swing.JMenuItem menStudentProfile;
    // End of variables declaration//GEN-END:variables
}
